Develop
rakutentech/ios-miniapp pull request #166
Opened 2020-11-12 03:36 UTC by Climbatize

# Description
The instructional and placeholder text were overlapping due to iOS 11 different behavior.

![Screen Shot 2020-11-12 at 12 30 36](https://user-images.githubusercontent.com/1507391/98892425-a1766880-24e3-11eb-8a26-5406b77510ae.png)

## Links
[MINI-2109](https://jira.rakuten-it.com/jira/browse/MINI-2109)

# Checklist
- [X] I have read the [contributing guidelines](../CONTRIBUTING.md).
- [ ] I wrote/updated tests for new/changed code
- [X] I removed all sensitive data before every commit, including API endpoints and keys
- [X] I ran `fastlane ci` without errors

2020-11-12 03:37 UTC, Climbatize commented on MiniApp/Classes/MiniAppDownloader.swift
> +                MiniAppLogger.d("📂 \(miniAppStoragePath.absoluteString)")
sorry for that, it's an artifact from another debug session

2020-11-12 03:58 UTC, ts-leojoseph-r requested changes
Looks like `js-miniapp` submodule is removed

2020-11-13 00:33 UTC, Climbatize commented
> Looks like `js-miniapp` submodule is removed

😖

2020-11-16 06:35 UTC, ts-leojoseph-r approved these changes
Looks good to me :+1:

2020-11-16 08:03 UTC, corycaywood approved these changes
Looks good 👍

2020-11-17 01:51 UTC, merged