SPM Update RAnalytics to 9.1.0 -> upToNextMajor
rakutentech/ios-miniapp pull request #413
Opened 2022-06-16 01:49 UTC by laubengaier

# Description
Update the RAnalytics version to 9.x to match Link

## Links
No Link

# Checklist
- [x] I have read the [contributing guidelines](CONTRIBUTING.md).
- [x] I have completed the [SDK Development Learning Path](CONTRIBUTING.md#SDK-Development-Learning-Path) (if submitting a feature PR)
- [x] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data before every commit, including API endpoints and keys
- [x] I ran `fastlane ci` without errors

2022-06-20 02:10 UTC, Climbatize approved these changes

2022-06-20 02:27 UTC, Climbatize requested changes
as we can see in the sample app podfile, RAT should be a sample app dependency:
```ruby
pod 'AppCenter/Crashes'
pod 'RAnalytics', :source => 'https://github.com/rakutentech/ios-analytics-framework.git'
```
So we should have these 2 libraries as dependencies for the SMP sample app and not the SDK

2022-06-20 04:18 UTC, Climbatize approved these changes

2022-06-21 00:28 UTC, rleojoseph approved these changes
Looks good to me :+1:

2022-06-21 01:39 UTC, merged